Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
=============== RESTART: C:/Users/IT PEC/Desktop/day/day_6.py ===============
10
this is class
>>> 
=============== RESTART: C:/Users/IT PEC/Desktop/day/day_6.py ===============
10
this is class
this is in class
the value is 100
>>> 
=============== RESTART: C:/Users/IT PEC/Desktop/day/day_6.py ===============
this is in class
the value is 100
>>> 
=============== RESTART: C:/Users/IT PEC/Desktop/day/day_6.py ===============
this obj value is 100
Traceback (most recent call last):
  File "C:/Users/IT PEC/Desktop/day/day_6.py", line 50, in <module>
    obj1=abc(100)
  File "C:/Users/IT PEC/Desktop/day/day_6.py", line 49, in __init__
    print("the  class value is",class_var)
NameError: name 'class_var' is not defined
>>> 
=============== RESTART: C:/Users/IT PEC/Desktop/day/day_6.py ===============
this obj value is 100
Traceback (most recent call last):
  File "C:/Users/IT PEC/Desktop/day/day_6.py", line 50, in <module>
    obj1=abc(100)
  File "C:/Users/IT PEC/Desktop/day/day_6.py", line 49, in __init__
    print("the  class value is",class_var)
NameError: name 'class_var' is not defined
>>> 
=============== RESTART: C:/Users/IT PEC/Desktop/day/day_6.py ===============
this obj value is 100
Traceback (most recent call last):
  File "C:/Users/IT PEC/Desktop/day/day_6.py", line 50, in <module>
    obj1= abc(100)
  File "C:/Users/IT PEC/Desktop/day/day_6.py", line 49, in __init__
    print("the  class value is",class_var)
NameError: name 'class_var' is not defined
>>> 
=============== RESTART: C:/Users/IT PEC/Desktop/day/day_6.py ===============
this obj value is 101
Traceback (most recent call last):
  File "C:/Users/IT PEC/Desktop/day/day_6.py", line 50, in <module>
    obj1= abc(101)
  File "C:/Users/IT PEC/Desktop/day/day_6.py", line 49, in __init__
    print("the  class value is",class_var)
NameError: name 'class_var' is not defined
>>> 
=============== RESTART: C:/Users/IT PEC/Desktop/day/day_6.py ===============
this obj value is 101
Traceback (most recent call last):
  File "C:/Users/IT PEC/Desktop/day/day_6.py", line 50, in <module>
    obj1= abc(101)
  File "C:/Users/IT PEC/Desktop/day/day_6.py", line 49, in __init__
    print("the  class value is",a_var)
NameError: name 'a_var' is not defined
>>> 
=============== RESTART: C:/Users/IT PEC/Desktop/day/day_6.py ===============
Traceback (most recent call last):
  File "C:/Users/IT PEC/Desktop/day/day_6.py", line 50, in <module>
    obj1= abc(101)
  File "C:/Users/IT PEC/Desktop/day/day_6.py", line 46, in __init__
    abc.class_var +=1
AttributeError: type object 'abc' has no attribute 'class_var'
>>> 
=============== RESTART: C:/Users/IT PEC/Desktop/day/day_6.py ===============
this obj value is 101
the  class value is 1
this obj value is 102
the  class value is 2
this obj value is 103
the  class value is 3
>>> 
=============== RESTART: C:/Users/IT PEC/Desktop/day/day_6.py ===============
Traceback (most recent call last):
  File "C:/Users/IT PEC/Desktop/day/day_6.py", line 65, in <module>
    n.even_odd(21)
AttributeError: 'num' object has no attribute 'even_odd'
>>> 
=============== RESTART: C:/Users/IT PEC/Desktop/day/day_6.py ===============
Traceback (most recent call last):
  File "C:/Users/IT PEC/Desktop/day/day_6.py", line 65, in <module>
    n.even_odd(21)
AttributeError: 'number' object has no attribute 'even_odd'
>>> 
=============== RESTART: C:/Users/IT PEC/Desktop/day/day_6.py ===============
Traceback (most recent call last):
  File "C:/Users/IT PEC/Desktop/day/day_6.py", line 65, in <module>
    n.even_odd(21)
AttributeError: 'number' object has no attribute 'even_odd'
>>> 
=============== RESTART: C:/Users/IT PEC/Desktop/day/day_6.py ===============
Traceback (most recent call last):
  File "C:/Users/IT PEC/Desktop/day/day_6.py", line 65, in <module>
    n.even_odd(21)
TypeError: 'int' object is not callable
>>> 
=============== RESTART: C:/Users/IT PEC/Desktop/day/day_6.py ===============
Traceback (most recent call last):
  File "C:/Users/IT PEC/Desktop/day/day_6.py", line 65, in <module>
    n.even_odd(21)
AttributeError: 'number' object has no attribute 'even_odd'
>>> 
=============== RESTART: C:/Users/IT PEC/Desktop/day/day_6.py ===============
Traceback (most recent call last):
  File "C:/Users/IT PEC/Desktop/day/day_6.py", line 65, in <module>
    n.even_odd(21)
AttributeError: 'number' object has no attribute 'even_odd'
>>> 
=============== RESTART: C:/Users/IT PEC/Desktop/day/day_6.py ===============
Traceback (most recent call last):
  File "C:/Users/IT PEC/Desktop/day/day_6.py", line 66, in <module>
    n.even_odd(21)
AttributeError: 'number' object has no attribute 'even_odd'
>>> 
=============== RESTART: C:/Users/IT PEC/Desktop/day/day_6.py ===============
area <bound method circle.area of <__main__.circle object at 0x000001BCD8FB00F0>>
circum <bound method circle.circumstance of <__main__.circle object at 0x000001BCD8FB00F0>>
>>> 
=============== RESTART: C:/Users/IT PEC/Desktop/day/day_6.py ===============
area <bound method circle.area of <__main__.circle object at 0x000002EBCACA8780>>
circum <bound method circle.circumstance of <__main__.circle object at 0x000002EBCACA8780>>
>>> 
